/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTopUpRouteImport } from './routes/_authenticated/top-up'
import { Route as AuthenticatedTariffsRouteImport } from './routes/_authenticated/tariffs'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authAuthRouteImport } from './routes/(auth)/auth'
import { Route as AuthenticatedSubscriptionsIndexRouteImport } from './routes/_authenticated/subscriptions/index'
import { Route as AuthenticatedSubscriptionsSubscriptionIdRouteImport } from './routes/_authenticated/subscriptions/$subscriptionId'
import { Route as AuthenticatedSubscriptionsSubscriptionIdLteRouteImport } from './routes/_authenticated/subscriptions/$subscriptionId_.lte'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTopUpRoute = AuthenticatedTopUpRouteImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTariffsRoute = AuthenticatedTariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscriptionsIndexRoute =
  AuthenticatedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionsSubscriptionIdRoute =
  AuthenticatedSubscriptionsSubscriptionIdRouteImport.update({
    id: '/subscriptions/$subscriptionId',
    path: '/subscriptions/$subscriptionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionsSubscriptionIdLteRoute =
  AuthenticatedSubscriptionsSubscriptionIdLteRouteImport.update({
    id: '/subscriptions/$subscriptionId_/lte',
    path: '/subscriptions/$subscriptionId/lte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof authAuthRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/tariffs': typeof AuthenticatedTariffsRoute
  '/top-up': typeof AuthenticatedTopUpRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/subscriptions/$subscriptionId': typeof AuthenticatedSubscriptionsSubscriptionIdRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsIndexRoute
  '/subscriptions/$subscriptionId/lte': typeof AuthenticatedSubscriptionsSubscriptionIdLteRoute
}
export interface FileRoutesByTo {
  '/auth': typeof authAuthRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/tariffs': typeof AuthenticatedTariffsRoute
  '/top-up': typeof AuthenticatedTopUpRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/subscriptions/$subscriptionId': typeof AuthenticatedSubscriptionsSubscriptionIdRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsIndexRoute
  '/subscriptions/$subscriptionId/lte': typeof AuthenticatedSubscriptionsSubscriptionIdLteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/auth': typeof authAuthRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/tariffs': typeof AuthenticatedTariffsRoute
  '/_authenticated/top-up': typeof AuthenticatedTopUpRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/subscriptions/$subscriptionId': typeof AuthenticatedSubscriptionsSubscriptionIdRoute
  '/_authenticated/subscriptions/': typeof AuthenticatedSubscriptionsIndexRoute
  '/_authenticated/subscriptions/$subscriptionId_/lte': typeof AuthenticatedSubscriptionsSubscriptionIdLteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/payments'
    | '/profile'
    | '/referrals'
    | '/tariffs'
    | '/top-up'
    | '/transactions'
    | '/'
    | '/subscriptions/$subscriptionId'
    | '/subscriptions'
    | '/subscriptions/$subscriptionId/lte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/payments'
    | '/profile'
    | '/referrals'
    | '/tariffs'
    | '/top-up'
    | '/transactions'
    | '/'
    | '/subscriptions/$subscriptionId'
    | '/subscriptions'
    | '/subscriptions/$subscriptionId/lte'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/auth'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/tariffs'
    | '/_authenticated/top-up'
    | '/_authenticated/transactions'
    | '/_authenticated/'
    | '/_authenticated/subscriptions/$subscriptionId'
    | '/_authenticated/subscriptions/'
    | '/_authenticated/subscriptions/$subscriptionId_/lte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authAuthRoute: typeof authAuthRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/top-up': {
      id: '/_authenticated/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof AuthenticatedTopUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tariffs': {
      id: '/_authenticated/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof AuthenticatedTariffsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscriptions/': {
      id: '/_authenticated/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions/$subscriptionId': {
      id: '/_authenticated/subscriptions/$subscriptionId'
      path: '/subscriptions/$subscriptionId'
      fullPath: '/subscriptions/$subscriptionId'
      preLoaderRoute: typeof AuthenticatedSubscriptionsSubscriptionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions/$subscriptionId_/lte': {
      id: '/_authenticated/subscriptions/$subscriptionId_/lte'
      path: '/subscriptions/$subscriptionId/lte'
      fullPath: '/subscriptions/$subscriptionId/lte'
      preLoaderRoute: typeof AuthenticatedSubscriptionsSubscriptionIdLteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedTariffsRoute: typeof AuthenticatedTariffsRoute
  AuthenticatedTopUpRoute: typeof AuthenticatedTopUpRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSubscriptionsSubscriptionIdRoute: typeof AuthenticatedSubscriptionsSubscriptionIdRoute
  AuthenticatedSubscriptionsIndexRoute: typeof AuthenticatedSubscriptionsIndexRoute
  AuthenticatedSubscriptionsSubscriptionIdLteRoute: typeof AuthenticatedSubscriptionsSubscriptionIdLteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedTariffsRoute: AuthenticatedTariffsRoute,
  AuthenticatedTopUpRoute: AuthenticatedTopUpRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSubscriptionsSubscriptionIdRoute:
    AuthenticatedSubscriptionsSubscriptionIdRoute,
  AuthenticatedSubscriptionsIndexRoute: AuthenticatedSubscriptionsIndexRoute,
  AuthenticatedSubscriptionsSubscriptionIdLteRoute:
    AuthenticatedSubscriptionsSubscriptionIdLteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authAuthRoute: authAuthRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
